{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codios.fullname" . }}
  labels:
    {{- include "codios.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  gateway-secret: {{ .Values.secrets.gatewaySecret | quote }}
  codios-private-key: {{ .Values.secrets.codiosPrivateKey | quote }}
  codios-public-key: {{ .Values.secrets.codiosPublicKey | quote }}
  codios-did: {{ .Values.secrets.codiosDid | quote }}
  license-key: {{ .Values.secrets.licenseKey | quote }}
  license-public-key: {{ .Values.secrets.licensePublicKey | quote }}
  resend-api-key: {{ .Values.secrets.resendApiKey | quote }}
  resend-from: {{ .Values.secrets.resendFrom | quote }}
  smtp-host: {{ .Values.secrets.smtpHost | quote }}
  smtp-user: {{ .Values.secrets.smtpUser | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | quote }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | quote }}
{{- end }}
